# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Get tag or commit id
      id: get-version-id
      uses: iawia002/get-tag-or-commit-id@v1

    # Impossible to build due to fatal error, so no ChangeLogs for now.
    # I've got no clue why this is happening tbh.
    # TODO: fix this.
    #- name: Generate changelog
    #  id: generate_changelog
    #  run: |
    #    start_sha=${{ github.event.before }}
    #    end_sha=${{ github.event.after }}

    #    if [[ $start_sha != $end_sha ]]; then
    #      mkdir changelogs
    #      echo "ChangeLogs:" > CHANGELOGS.txt
    #      git log --pretty=format:'- [ %ad ] ( #https://github.com/GrimAnticheat/Grim/commit/%h ) %s by %an' --date=format:'%d-%m-%Y | %I:%M%p' $start_sha..$end_sha >> CHANGELOGS.txt
    #    fi
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build

    - name: Release to Github
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          build/libs/**.jar
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: ${{ steps.get-version-id.outputs.id }}
        #body_path: CHANGELOGS.txt
        draft: false
        prerelease: false

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        path: /home/runner/work/Grim/Grim/build/libs/**.jar
